---
- hosts: all
  sudo: yes
  tasks:
    - name: disable all repos by default
      shell: subscription-manager repos --disable="*"      
    - name: Enable the requisite rhel7 repos
      shell: subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-7-server-optional-rpms"
    - name: Import keys
      rpm_key: state=present key=/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-beta
    - name: Remove Network Manager
      yum: name=NetworkManager state=absent
    - name: Install pre requisites
      yum: name={{ item }} state=present
      with_items:
          - wget
          - git
          - unzip
          - net-tools
          - bind-utils
          - iptables-services
          - bridge-utils
          - tmux
    - name: Update all yum packages
      yum: name=* state=latest
    - name: Install Docker
      yum: name=docker state=present
    - name: Enable insecure registry... since we like insecure things
      lineinfile: dest=/etc/sysconfig/docker state=present line='OPTIONS=--insecure-registry 172.30.0.0/16' regexp="^#?OPTIONS" 
    - name: Start docker
      service: name=docker state=started enabled=yes
      
